- src/pages/review/Review.vue
- src/router/index.js
> [Feat] 리뷰 헤더, 푸터 적용

- src/pages/payment/paymentComponents/menu.vue
- src/pages/payment/paymentComponents/orderList.vue
- src/pages/payment/paymentComponents/payList.vue
- src/pages/payment/paymentDetails.vue
- src/pages/payment/paymentList.vue
- src/pages/review/Review.vue
- src/stores/usePaymentStore.js
> [Fix] 주문목록 드롭다운 #9

- src/pages/payment/paymentDetails.vue
- src/pages/payment/paymentList.vue
> 주문상세 페이지 if문 추가 #13

- src/pages/payment/paymentList.vue
> [Fix] 주문목록 input창 업데이트 #20

- back/app.js
- back/package-lock.json
- back/package.json
- src/pages/payment/paymentDetails.vue
- src/router/index.js
- src/stores/usePaymentStore.js
> [Feat] express 추가 #23

- src/pages/common/Header.vue
- src/stores/usePaymentStore.js
> [fix] paymentStore 주소 조정 #32

- src/pages/home/HomeBookList.vue
- src/pages/productDetail/ProductDetail.vue
- src/router/index.js
- src/stores/useMainBookStore.js
- src/stores/useResultBookStore.js
상품상세에서 채팅방 이동 기능 추가
홈 화면에서 이미지 전부 나오도록 store 수정
상품 상세 눌렀을 때 해당 책 아이디에 맞는 상세 페이지 나오도록 수정
close #35
> [Feat] 상품 상세에서 채팅 이동 기능 추가 #35

- index.html
- src/pages/payment/paymentComponents/menu.vue
- src/pages/payment/paymentList.vue
> [Fix] paymentList 에러 해결 #37

- src/router/index.js
> [Fix] changes in showing Footer on the Chatroom page

- src/pages/home/Home.vue
- src/pages/home/HomeSearchField.vue
- src/pages/home/HomeTitle.vue
- A fix in a link for button element
- Refactor all script tags to use script setup
> [Fix] Code refactoring & fixes in Links

- src/pages/home/ResultBookList.vue
> [Fix] Refactor router-link path attributes to match new route setup

- src/pages/common/Header.vue
> [Fix] A minor change in router link element

- src/pages/home/HomeBookList.vue
- src/pages/productDetail/ProductDetail.vue
Home 컴포넌트와 SearchResult 컴포넌트에서 재사용되는 HomeBookList에 onWishButton 메서드 적용 및 로그인 모달 적용
> [Feat] Add wishButton feature on Home component as well

- src/pages/common/Header.vue
- src/stores/useMainBookStore.js
> [Fix] header에서 내상품 이동경로 수정

- src/pages/common/Header.vue
- src/stores/useMainBookStore.js
> [Fix] myImformation추가

- src/pages/common/Header.vue
- src/stores/useMainBookStore.js
> [Fix] myproductstores url수정

- src/pages/payment/paymentComponents/menu.vue
- src/pages/payment/paymentList.vue
- src/stores/usePaymentStore.js
> [FIx] orderList api연결

- src/pages/common/Header.vue
- src/pages/payment/paymentComponents/orderList.vue
> [Fix] 주문정보 url 수정

- src/pages/payment/paymentComponents/orderList.vue
- src/pages/payment/paymentList.vue
- src/stores/usePaymentStore.js
> [Fix] orderList 백엔드 연결

- src/pages/payment/paymentComponents/payList.vue
- src/pages/payment/paymentList.vue
- src/stores/usePaymentStore.js
> [fix] 판매조회 백엔드 연결

- src/pages/payment/paymentComponents/orderList.vue
- src/pages/payment/paymentDetails.vue
- src/router/index.js
- src/stores/usePaymentStore.js
> [fix] 주문 상세정보 보기 백 연동

- src/pages/mypage/Myproduct_home.vue
- src/pages/payment/paymentComponents/orderList.vue
- src/pages/payment/paymentDetails.vue
- src/pages/payment/paymentList.vue
- src/router/index.js
- src/stores/usePaymentStore.js
> [Fix] 주문정보 무한 스크롤

- src/pages/mypage/Myproduct_home.vue
- src/pages/mypage/Myproductstores.vue
- src/stores/useProductReview.js
- src/stores/useProductStore.js
> [Error]에러나는거 수정 했습니다.

- src/pages/mypage/Myproduct_home.vue
- src/pages/mypage/Myproductstores.vue
- src/stores/useProductReview.js
- src/stores/useProductStore.js
> [Error]에러 최종 수정 입니다.

- src/pages/mypage/Myproductstores.vue
- src/pages/mypage/MystoreReviews.vue
- src/router/index.js
내 게시물이 최근 등록순으로 출력하는 기능을 추가 했습니다.
> [feat]내 게시물이 최근 등록순으로 출력

- src/pages/common/WishList.vue
> [feat] 최종 찜목록 페이지 올립니다.

- src/pages/common/Header.vue
- src/router/index.js
- src/stores/useMemberStore.js
> [feat]찜목록페이지 찐 최종올립니다.
